/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul2;

import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author BERLANDA GULTOM
 */
public class BakeToMe extends javax.swing.JFrame {

    /**
     * Creates new form BakeToMe
     */
    public BakeToMe() {
        initComponents();
        jumlah.setText("1");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        baketome = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        FRAMEMAN = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        focaccia = new javax.swing.JRadioButton();
        garlic = new javax.swing.JRadioButton();
        redbeans = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        brown = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stick = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        crumpet = new javax.swing.JRadioButton();
        toppings = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        TAMBAH = new javax.swing.JButton();
        TOTAL = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        RESET = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        chocolate = new javax.swing.JRadioButton();
        cheese = new javax.swing.JRadioButton();
        peanut = new javax.swing.JRadioButton();
        notopings = new javax.swing.JRadioButton();
        KURANG = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 102, 153)));

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        baketome.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        baketome.setForeground(new java.awt.Color(255, 255, 255));
        baketome.setText("Bake To Me");

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/baketome_1_11zon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(18, 18, 18)
                .addComponent(baketome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Logo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(baketome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menu.setBackground(new java.awt.Color(255, 102, 153));
        menu.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        menu.setForeground(new java.awt.Color(255, 102, 153));
        menu.setText("Menu :");

        FRAMEMAN.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        FRAMEMAN.setForeground(new java.awt.Color(255, 102, 153));
        FRAMEMAN.setText("------------------------------");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/focaccia bread_3_11zon-fotor-2024100594053.jpg"))); // NOI18N

        buttonGroup1.add(focaccia);
        focaccia.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        focaccia.setText("Focaccia Bread-Rp.40.000");

        buttonGroup1.add(garlic);
        garlic.setFont(new java.awt.Font("Script MT Bold", 0, 14)); // NOI18N
        garlic.setText("Garlic Bread-Rp.25.000");

        buttonGroup1.add(redbeans);
        redbeans.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        redbeans.setText("Red Beans Bread-Rp.35.000");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/red beans bread_7_11zon-fotor-2024100594228.jpg"))); // NOI18N

        buttonGroup1.add(brown);
        brown.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        brown.setText("Brown Bread-Rp.40.000");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Garlic Bread_4_11zon-fotor-2024100594115.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/11zon_resized (2)-fotor-2024100593148.png"))); // NOI18N

        buttonGroup1.add(stick);
        stick.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        stick.setText("Bread Stick-Rp.18.000");
        stick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stickActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/crumpet_2_11zon-fotor-2024100593933.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/breadstick_1_11zon-fotor-2024100593721.jpg"))); // NOI18N

        buttonGroup1.add(crumpet);
        crumpet.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        crumpet.setText("Crumpet-Rp.21.000");

        toppings.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        toppings.setForeground(new java.awt.Color(255, 102, 153));
        toppings.setText("Toppings :");

        jLabel11.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel11.setText("Jumlah :");

        jumlah.setBackground(new java.awt.Color(255, 102, 153));
        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });

        TAMBAH.setBackground(new java.awt.Color(255, 102, 153));
        TAMBAH.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        TAMBAH.setText("+");
        TAMBAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TAMBAHActionPerformed(evt);
            }
        });

        TOTAL.setBackground(new java.awt.Color(255, 102, 153));
        TOTAL.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        TOTAL.setText("Total (Rp)");
        TOTAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TOTALActionPerformed(evt);
            }
        });

        total.setBackground(new java.awt.Color(255, 102, 153));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel13.setText("Bayar (Rp):");

        jLabel14.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        jLabel14.setText("Kembali (Rp):");

        cash.setBackground(new java.awt.Color(255, 102, 153));
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        kembali.setBackground(new java.awt.Color(255, 102, 153));

        RESET.setBackground(new java.awt.Color(255, 102, 153));
        RESET.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        RESET.setText("RESET");
        RESET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESETActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 102, 153));

        jPanel4.setBackground(new java.awt.Color(255, 102, 153));

        buttonGroup7.add(chocolate);
        chocolate.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        chocolate.setText("Chocolate-Rp.5000");

        buttonGroup7.add(cheese);
        cheese.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        cheese.setText("Cheese-Rp.6000");
        cheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheeseActionPerformed(evt);
            }
        });

        buttonGroup7.add(peanut);
        peanut.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        peanut.setText("Peanut -Rp.4000");
        peanut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peanutActionPerformed(evt);
            }
        });

        buttonGroup7.add(notopings);
        notopings.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        notopings.setText("No Toping");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chocolate, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheese, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peanut)
                    .addComponent(notopings, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chocolate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cheese)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(peanut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notopings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        KURANG.setBackground(new java.awt.Color(255, 102, 153));
        KURANG.setFont(new java.awt.Font("Script MT Bold", 1, 14)); // NOI18N
        KURANG.setText("-");
        KURANG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KURANGActionPerformed(evt);
            }
        });

        TA.setBackground(new java.awt.Color(255, 102, 153));
        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FRAMEMAN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(323, 323, 323))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(45, 45, 45)
                                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(57, 57, 57)
                                .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(222, 222, 222)
                        .addComponent(RESET)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(redbeans)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel4))
                                    .addComponent(focaccia))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(garlic)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(47, 47, 47)
                                                .addComponent(jLabel6)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(65, 65, 65)
                                                .addComponent(jLabel8))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(crumpet))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(brown)
                                        .addGap(18, 18, 18)
                                        .addComponent(stick))))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(136, 136, 136)
                                    .addComponent(jLabel5)
                                    .addGap(88, 88, 88)
                                    .addComponent(jLabel7))
                                .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(toppings, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(KURANG)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TAMBAH))
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(TOTAL)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jScrollPane1)
                                    .addComponent(total))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(631, Short.MAX_VALUE)
                    .addComponent(jLabel30)
                    .addGap(33, 33, 33)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(FRAMEMAN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crumpet, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(focaccia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(garlic)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redbeans)
                    .addComponent(brown)
                    .addComponent(stick))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(toppings, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TOTAL)
                                .addGap(97, 97, 97)))
                        .addGap(39, 39, 39)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(TAMBAH)
                                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(KURANG)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addComponent(cash, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(RESET)
                .addGap(16, 16, 16)
                .addComponent(jLabel12)
                .addGap(0, 7, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(648, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stickActionPerformed
        
    }//GEN-LAST:event_stickActionPerformed

    private void cheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheeseActionPerformed
        
    }//GEN-LAST:event_cheeseActionPerformed

    private void peanutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peanutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peanutActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
    }//GEN-LAST:event_jumlahActionPerformed

    private void TAMBAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TAMBAHActionPerformed
        int JUMLAH = Integer.parseInt(jumlah.getText());
            JUMLAH++;
            jumlah.setText(String.valueOf(JUMLAH));
            
    }//GEN-LAST:event_TAMBAHActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
       // Pastikan kedua field (tftotal dan tfcash) tidak kosong
    if (!total.getText().isEmpty() && !cash.getText().isEmpty()) {
        int totalHarga = Integer.parseInt(total.getText());
        int bayar = Integer.parseInt(cash.getText());
        
        if (bayar >= totalHarga) {
            int kembalian = bayar - totalHarga;
            kembali.setText(String.valueOf(kembalian));
        } else {
           JOptionPane.showMessageDialog(null, "Uang tidak cukup!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            kembali.setText("");
            kembali.setEditable(false);
        }
    }
    }//GEN-LAST:event_cashActionPerformed

    private void KURANGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KURANGActionPerformed
        int JUMLAH = Integer.parseInt(jumlah.getText());
            if (JUMLAH >= 2){
                JUMLAH--;
                jumlah.setText(String.valueOf(JUMLAH));
    }else{
            JOptionPane.showMessageDialog(null, "Tidak boleh nol!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
            
    }//GEN-LAST:event_KURANGActionPerformed

    private void RESETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESETActionPerformed
        buttonGroup1.clearSelection();
        buttonGroup7.clearSelection();
        jumlah.setText("1");
        total.setText("");
        cash.setText("");
        kembali.setText("");
        TA.setText("");
    }//GEN-LAST:event_RESETActionPerformed

    private void TOTALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TOTALActionPerformed
    int totalPrice = 0;
        //MENU
        if (focaccia.isSelected()) {
            totalPrice += 40000;
        } else if (garlic.isSelected()) {
            totalPrice += 25000;
        } else if (redbeans.isSelected()) {
            totalPrice += 35000;
        } else if (brown.isSelected()) {
            totalPrice += 40000;
        } else if (stick.isSelected()) {
            totalPrice += 18000;
        } else if (crumpet.isSelected()) {
            totalPrice += 21000;
        }
        if (!focaccia.isSelected() && !garlic.isSelected() && !redbeans.isSelected() && !brown.isSelected() && !stick.isSelected() && !crumpet.isSelected()) {
        JOptionPane.showMessageDialog(null, "Silakan pilih menu terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        //TOPPINGS
        if (chocolate.isSelected()) {
            totalPrice += 5000;
        } else if (cheese.isSelected()) {
            totalPrice += 6000;
        } else if (peanut.isSelected()) {
            totalPrice += 4000;
        }
        if (!chocolate.isSelected() && !cheese.isSelected() && !peanut.isSelected() && !notopings.isSelected()) {
            JOptionPane.showMessageDialog(null, "Silakan pilih toping terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //JUMLAH 
         if (jumlah.getText().isEmpty() || jumlah.getText().equals("0")) {
            JOptionPane.showMessageDialog(null, "Silakan masukkan jumlah terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
            }
         //TOTAL 
        int jumlahBeli = Integer.parseInt(jumlah.getText());
        totalPrice *= jumlahBeli;
        // DISKON
        int hargaSebelumDiskon = totalPrice;
        if (totalPrice > 100000) {
            totalPrice = (int) (totalPrice * 0.95); // 5% discount
        }
        String infoHarga = "Harga sebelum diskon: Rp" + hargaSebelumDiskon + "\n";
        if (hargaSebelumDiskon != totalPrice) {
            infoHarga += "Diskon: 5% (Rp" + (hargaSebelumDiskon - totalPrice) + ")\n";
        }
        infoHarga += "Total harga: Rp" + totalPrice;
        TA.setText(infoHarga);
        TA.setEditable(false);
        
        total.setText(String.valueOf(totalPrice));
        total.setEditable(false);
    }//GEN-LAST:event_TOTALActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakeToMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakeToMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakeToMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakeToMe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakeToMe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FRAMEMAN;
    private javax.swing.JButton KURANG;
    private javax.swing.JLabel Logo;
    private javax.swing.JButton RESET;
    private javax.swing.JTextArea TA;
    private javax.swing.JButton TAMBAH;
    private javax.swing.JButton TOTAL;
    private javax.swing.JLabel baketome;
    private javax.swing.JRadioButton brown;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JTextField cash;
    private javax.swing.JRadioButton cheese;
    private javax.swing.JRadioButton chocolate;
    private javax.swing.JRadioButton crumpet;
    private javax.swing.JRadioButton focaccia;
    private javax.swing.JRadioButton garlic;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembali;
    private javax.swing.JLabel menu;
    private javax.swing.JRadioButton notopings;
    private javax.swing.JRadioButton peanut;
    private javax.swing.JRadioButton redbeans;
    private javax.swing.JRadioButton stick;
    private javax.swing.JLabel toppings;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
